package tokenize

// SecurityTerms is the domain-specific dictionary for security terminology.
var SecurityTerms = []string{
	// Multi-word Chinese terms (longest first)
	"远程代码执行", "跨站请求伪造", "服务端请求伪造", "本地文件包含",
	"远程文件包含", "XML外部实体", "不安全反序列化", "服务器端模板注入",
	"操作系统命令注入", "二阶SQL注入", "基于时间的盲注", "基于布尔的盲注",
	"基于报错的注入", "基于联合查询注入", "HTTP请求走私", "HTTP参数污染",
	"服务端包含注入", "跨站脚本攻击", "横向移动", "权限提升",
	"持久化", "命令执行", "代码执行", "文件上传", "文件包含",
	"目录遍历", "信息泄露", "逻辑漏洞", "越权访问", "未授权访问",
	"弱口令", "暴力破解", "密码喷洒", "凭据填充", "会话劫持",
	"会话固定", "中间人攻击", "域名劫持", "子域名接管", "DNS重绑定",
	"供应链攻击", "水坑攻击", "钓鱼攻击", "社会工程", "内网渗透",
	"域渗透", "红队", "蓝队", "紫队", "漏洞扫描", "漏洞利用",
	"后渗透", "免杀技术", "反弹Shell", "提权漏洞",
	// AD domain attack Chinese terms
	"委派攻击", "非约束委派", "约束委派", "基于资源的约束委派",
	"域信任", "林信任", "父子域", "跨林攻击", "信任关系",
	"黄金票据", "白银票据", "钻石票据", "骨架密钥",
	"凭据导出", "哈希传递", "票据传递", "过度哈希传递",
	"域持久化", "计划任务", "注册表持久化", "WMI事件订阅",
	// Common Chinese compound terms (avoid bigram cross-boundary breakage)
	"应急响应", "密码字典", "容器逃逸", "反序列化", "代码审计",
	"安全审计", "入侵排查", "日志分析", "进程排查", "账户审计",
	"后门检测", "安全事件", "端口扫描", "存活探测", "指纹识别",
	"流量分析", "安全评估", "渗透测试", "漏洞挖掘", "安全加固",
	"入侵检测", "数据库", "注册表", "命令注入", "文件读取",
	"文件写入", "路径穿越", "配置错误", "云安全", "网络安全",
	"应用安全", "零日漏洞", "口令爆破", "痕迹清理", "网络连接",
	"启动项", "木马查杀", "权限维持", "域控", "内网",
	// Two-char Chinese terms
	"注入", "提权", "爆破", "枚举", "扫描", "渗透", "绕过",
	"利用", "劫持", "伪造", "欺骗", "嗅探", "重放", "逆向",
	"脱壳", "加壳", "混淆", "反编译", "漏洞", "后门", "木马",
	// English terms
	"SQL Injection", "Cross-Site Scripting", "XSS", "CSRF", "SSRF",
	"XXE", "LFI", "RFI", "RCE", "IDOR", "SSTI", "CRLF",
	"LDAP Injection", "NoSQL Injection", "Command Injection",
	"Path Traversal", "Directory Traversal", "File Upload",
	"Deserialization", "Prototype Pollution", "DOM Clobbering",
	"HTTP Smuggling", "HTTP Parameter Pollution", "HPP",
	"Server-Side Includes", "SSI", "Open Redirect",
	"Clickjacking", "CORS Misconfiguration", "JWT",
	"OAuth", "SAML", "Kerberos", "Kerberoasting", "AS-REP Roasting",
	"Pass-the-Hash", "Pass-the-Ticket", "Golden Ticket", "Silver Ticket",
	"DCSync", "DCShadow", "BloodHound", "Mimikatz", "Rubeus",
	"Responder", "Impacket", "CrackMapExec", "Evil-WinRM",
	"Metasploit", "Cobalt Strike", "Burp Suite",
	"Nmap", "Masscan", "Nuclei", "SQLMap", "Nikto", "Gobuster",
	"Ffuf", "Dirsearch", "Subfinder", "Amass", "httpx",
	"OWASP", "MITRE ATT&CK", "CVE", "CWE", "CVSS",
	"Privilege Escalation", "Lateral Movement", "Persistence",
	"Defense Evasion", "Credential Access", "Initial Access",
	"Reconnaissance", "Resource Development", "Execution",
	"Discovery", "Collection", "Exfiltration",
	"Command and Control", "C2", "Reverse Shell", "Web Shell",
	"Bind Shell", "Meterpreter", "Beacon",
	"Buffer Overflow", "Heap Overflow", "Stack Overflow",
	"Use After Free", "Format String", "Race Condition",
	"TOCTOU", "Integer Overflow", "Null Pointer Dereference",
	"Active Directory", "Domain Controller", "Group Policy",
	"Unconstrained Delegation", "Constrained Delegation", "Resource-Based Constrained Delegation",
	"Domain Trust", "Forest Trust", "SID History", "SID Filtering",
	"Diamond Ticket", "Skeleton Key", "AdminSDHolder",
	"Overpass-the-Hash", "RBCD", "S4U2Self", "S4U2Proxy",
	"PetitPotam", "PrinterBug", "DFSCoerce", "ShadowCoerce",
	"KrbRelayUp", "AMSI", "NetExec", "Sliver",
	"NTLM Relay", "SOCKS5", "Named Pipe", "DSRM",
	"WMI", "PSExec", "DCOM", "WinRM", "SMB", "RDP", "SSH",
	"AWS", "Azure", "GCP", "S3 Bucket", "EC2", "IAM",
	"Lambda", "CloudTrail", "Kubernetes", "Docker",
	"Container Escape", "SSRF to Cloud Metadata",
	"WAF", "IDS", "IPS", "EDR", "SIEM", "SOC",
	"Brute Force", "Dictionary Attack", "Rainbow Table",
	"Hashcat", "John the Ripper", "Hydra",
	"Phishing", "Spear Phishing", "Whaling",
	"Vishing", "Smishing", "Watering Hole",
	"Supply Chain", "Typosquatting",
	"Subdomain Takeover", "DNS Rebinding",
	"DNSSEC", "Zone Transfer",
}
